@url = http://localhost:4111

### BASE
{{url}}

### ALL FLASHCARDS
{{url}}/flashcards

### SINGLE FLASHCARD 
{{url}}/flashcards/2678

### ALL FLASHCARDS IN A CATEGORY
{{url}}/flashcards/category/git

